### ISSUE TITLE
i2 Connect - Limited Number of Records rendered

### ISSUE THREAD

**Issue by logicalis-i2** [i2group/analyze-connect#12]
Hello!
Just to know whether is it possible to configure the limitation of records rendered by a i2 connect search.
We are right now receiving the message of the 10.000 records limit.

Can we change that? If yes, where?
Thanks!

**Comment by Anthony-Johnson-i2** [comment]
Hi Luis 

That limit is the default we have set for how many results can be returned to the gateway.

It **is** configurable but we have not included the controlling property for that in our configuration files or documentation.

As part of an i2 Connect data retrieval,  results are dynamically Indexed in a temporary  Solr daod-index  so we have set this as a default limit to help keep things responsive,  especially in multi user systems with  expected overlapping  i2 Connect searches running.

The customer should consider carefully if they really want/need more than that many results to be returned or if they would be better to provide more tightly constrained/configurable  searching instead.

Cheers

Cheers

**Comment by Anthony-Johnson-i2** [comment]
Hi @logicalis-i2  Luis

I am just checking back to make sure you saw my reply to your question at the beginning of  March and that the record limit can be increased.

Cheers

**Comment by Anthony-Johnson-i2** [comment]
Excellent, thank you Luis.

**Comment by RaymondVA** [comment]
Hi!

I tried following the instructions but in DiscoServerSettingsCommon, this is the closest to "MaxExternalRecordsToFetch=20000":
# The maximum number of values in the value list of a visual query condition.
VisualQueryMaxValuesInList=10000

I modified the value to 20000 and saved it, then I ran setup -t deploy, then setup -t start, the max results stay the same 10000 records retrievable. I went back into DiscoServerSettingsCommon and found out that 20000 reverted back to 10000.

Could you help me make the modification to 20000?

**Comment by Colvin-Cowie-i2** [comment]
Hello again, so two things.

1. `MaxExternalRecordsToFetch` isn't in any of the property files that are provided in the example configuration, just add it on a new line at the end of the file.

e.g.
```
# The period after which a user who has accepted the privacy agreement must read and accept it again.
# When this property has no value, users do not see the agreement again until the mechanism is reset.
PrivacyAcceptancePeriodDays=

# Enables the generation of server metrics for the consumption of monitoring software such as Prometheus.
EnableMetrics=false

MaxExternalRecordsToFetch=20000
```

2. You should always modify the property files in your toolkit/configuration/fragments directory. They will overwrite the files that are deployed in the liberty application when you run `setup -t deploy` or `setup -t deployLiberty`.

**Comment by RaymondVA** [comment]
Hi Colvin,

Thanks a lot. I tested it and it worked!

Raymond 👍
