### ISSUE TITLE
Calling POST /v1/gateway/reload from the REST API does not reload connector gateway

### ISSUE THREAD

**Issue by abristow3** [i2group/analyze-connect#17]
I've followed along the guide in: [developer guide](https://www.ibm.com/docs/en/SSXVTH_4.3.2/com.ibm.i2.connect.developer.doc/connect_developer_guide_pdf.pdf#unique_18) to reload the connector gateway using the REST API method but with no success.

I receive an HTTP 200 OK response when calling this endpoint, but the gateway doesn't actually reload. When reloading through the GUI via the admin console it works as expected.

I've copied and used the URL generated by the /opal/docs endpoint as well when trying out the REST call with no luck. To note it reloads the gateway when using that endpoint through the /opal/docs "try it out" feature.

When calling POST /v1/gateway/reload from a separate container / application, are we supposed to pass in a token and or credentials for the server to validate against? I don't see that mentioned anywhere in the documentation though.

**Comment by Colvin-Cowie-i2** [comment]
Hello.

Can you confirm, are you trying to POST to `/v1/gateway/reload` or `/opal/v1/gateway/reload`? You need to include the context root (opal) in the path, e.g. https://localhost/opal/api/v1/gateway/reload

Since you say that reload is working when you do it through the Admin UI and "try it out" it sounds like you're going to the wrong path and you maybe have an HTTP server or proxy in front of the Liberty application that is returning the 200 response.
If you go direct to Liberty and omit the /opal/ it should return a 404 response.

A successful reload command will always return a response body. Does the response to your request contain a body?

**Comment by abristow3** [comment]
I am getting the header from the /j_security_check endpoint and see Set-Cookie in it, but it has an empty value.

`
"'Content-Length': '799', 'Set-Cookie': "
`

I believe I am passing in the credentials incorrectly in the post request. Do you have an example of how the j_username and j_password need to be passed in when using the python requests library? 

I've tried a few variations of the blow code:

```   
cookie_header = {'Content-Type': 'application/x-www-form-urlencoded'}
cookie_params = f"j_username={j_username}&j_password={j_password}"
cookie_url = f"https://i2a.cda.ascolta.systems:443/opal/j_security_check?{cookie_params}"
r = requests.post(url=cookie_url, headers=cookie_header, verify=False)
```

**Comment by abristow3** [comment]
Am able to generate a cookie just fine when running the curl commands in the example with my credentials, just issues when translating it to a requests.post() in python.

curl --cacert trust_chain.pem -d "j_username=<username>&j_password=<password_url_encoded>" --dump-header headers https://i2a.cda.ascolta.systems/opal/j_security_check

**Comment by Colvin-Cowie-i2** [comment]
Add `allow_redirects=False` to your `post()` and that should sort it. That `requests` library is following redirects by default

```
cookie_header = {'Content-Type': 'application/x-www-form-urlencoded'}
cookie_params = f"j_username={j_username}&j_password={j_password}"
cookie_url = f"https://i2a.cda.ascolta.systems:443/opal/j_security_check?{cookie_params}"
r = requests.post(url=cookie_url, allow_redirects=False, headers=cookie_header, verify=False)
print(r.cookies['LtpaToken2'])
```

**Comment by abristow3** [comment]
I've got it working now, had a small typo in my params after implementing your code. I fixed it and it is returning the cookie now!

Thanks for your help with this issue.
