### ISSUE TITLE
Docs: unclear validation response description

### ISSUE THREAD

**Issue by SchreiberLex** [i2group/analyze-connect#2]
The documentation about the server sided validation is ambiguous about the response the validation endpoint has to send back (described in point 3 of Version 1.0.1) which led to a few hours of try and error before i searched for a validation file inside the project which solved my problem.
I would suggest you reference the ValidationResponse file or add a clear technical description about the response (i e.g. interpreted a null response as an empty http response body).

**Comment by matthadf** [comment]
Thank you for the comment SchreiberLex, we will try to update the example the next time that repository is updated.

Thanks.
