### ISSUE TITLE
Connector service authentication in Python

### ISSUE THREAD

**Issue by RafaelCastilhoCastro** [i2group/analyze-connect#20]
Hi,
We have a Python connector which accesses and consumes a webservice. After the user logs in on ANB we need them to input an username and password when accessing the connector's services. The issue we're facing is that the route set on "loginUrl" in "authConfigs" (config.json file) is not being called and the username and password prompt is not appearing even when the "acquireUrl" endpoint returns a RFC7807 object (as it should in case of unauthenticated access if I understood correctly). Can you advise on what might be the problem on our approach?

Thanks for the help.

**Comment by Afira-Zahari-i2** [comment]
Hello,

> username and password prompt is not appearing even when the "acquireUrl" endpoint returns a RFC7807 object

The "acquireUrl" endpoint should return an RFC7807 object if the Authorization header does not have the bearer token (see [Implementing authentication verification on endpoints](https://i2group.github.io/analyze-connect/content/example-connectors/connector-auth.html#4-implementing-authentication-verification-on-endpoints)). That token will be sent from the i2 Connect gateway when the user has successfully logged in through the "login" endpoint.

Is the `authConfigId` defined for the service that requires the authentication? The prompt will appear when the gateway sees that the service has defined an `authConfigId`. 

For reference, the outline for the `services` and `authConfigs` objects in your config.json file should be similar to this https://github.com/i2group/analyze-connect/blob/master/connector/auth/auth-connector/src/main/resources/config.json.

**Comment by RafaelCastilhoCastro** [comment]
Hi, thanks for your response.

Yes, the "authConfigId" is defined according to the piece of documentation you linked. It looks simple enough but the prompt does not appear.

```
{
  "defaultValues": {
    "timeZoneId": "America/Sao_Paulo",
    "resultIdsPersistent": true
  },
  "schemaUrl": "/schema",
  "chartingSchemesUrl": "/charting_schemes",
  "schemaShortName": "Schema1",
  "services": [
    {
      "authConfigId": "authConfig1",
      "id": "CpfCnpj",
      "name": "Busca por CPF ou CNPJ",
      "description": "Buscar por CPF ou CNPJ",
      "acquireUrl": "/search_cpf_cnpj",
      "clientConfigType": "FORM",
      "clientConfigId": "acquire_cpf_cnpj"
    }
  ],
  "clientConfigs": [
    {
      "id": "acquire_cpf_cnpj",
      "config": {
        "sections": [
          {
            "conditions": [
              {
                "id": "cpf/cnpj",
                "label": "Busca por CPF ou CNPJ (Somente números).",
                "mandatory": true,
                "logicalType": "SINGLE_LINE_STRING"
              }
            ]
          }
        ]
      }
    }
  ],
  "authConfigs": [
    {
      "id": "authConfig1",
      "loginUrl": "/login",
      "form": {
        "description": "Esse serviço requer autenticação.",
        "fields": [
          {
            "id": "username",
            "label": "Usuário",
            "type": "text"
          },
          {
            "id": "password",
            "label": "Senha",
            "type": "password"
          }
        ]
      }
    }
  ]
}
```

Although the "acquireUrl" is returning this RFC7807 object below, the "loginUrl" is never being called.

```
{
            "detail": "Unauthorized",
            "instance": "https://www.example.com/errors/unauthorized",
            "status": 401,
            "title": "Unauthorized",
            "type": "urn:uuid:264caa46-75cb-4ac5-891a-11adeb48b6fb"
}
```

Can you spot any mistake on my configurations?

Thanks for your support.

**Comment by RafaelCastilhoCastro** [comment]
Yes, I'm using i2 Analyze server version 4.4.1

I reloaded the endpoints using the Postman method and all seems to be working as intended.
The response displayed these 3 warnings:
                {
                    "level": "WARNING",
                    "message": "Configuration error for the connector with identifier 'Q-Cred': The application is communicating with the connector through a protocol that is not secure."
                },
                {
                    "level": "WARNING",
                    "message": "The connector with identifier 'Q-Cred' did not specify an SPI version. Defaulting to version 1.0"
                },
                {
                    "level": "WARNING",
                    "message": "The connector with identifier 'Q-Cred' provides a charting scheme resource that contains more than one charting scheme. Only the first charting scheme will be used."
                }

It seems they're not related to the issue.
Hey Afira, just to be sure I managed to explain my problem correctly let me just elaborate on it. The issue is related to specific connector services that should require authentication after the user successfully performs the login into ANB, ok?

**Comment by Afira-Zahari-i2** [comment]
Hi @RafaelCastilhoCastro,

I understand your problem and I've verified that your configuration file is valid. I have applied your config over the example Auth connector (with some URL tweaks in the ConnectorController) and the login form for the service shows up.

![image](https://github.com/i2group/analyze-connect/assets/97247580/679bcc70-b861-434e-9f93-ba88098eea43)

The issue you're facing might have to do with your connector implementation. Your acquire endpoint shows that it's returning an RFC7806 object with a `401` status in it. Can you verify that the _response_ itself is returning a `401` status code and that the content type is `application/problem+json`? 

Just to clarify, the `401` status in the RFC7806 (`ProblemDetails`) object is different to the one returned by the endpoint itself. Both values have to be set correctly.

This is how it looks like in Java https://github.com/i2group/analyze-connect/blob/master/connector/auth/auth-connector/src/main/java/com/i2group/auth/ExternalConnectorDataService.java#L268.

It both are set correctly, can you see if there's any warnings or errors in your server logs?

Another thing you can do to check that your connector implementation is correct is by calling the connector services directly by using Postman. There are some [sample auth requests](https://i2group.github.io/analyze-connect/content/miscellaneous/postman.html#auth-requests) that you can use but you will have to update the endpoint to match the url that you've specified in your config.json.

**Comment by Anthony-Johnson-i2** [comment]
Hi @RafaelCastilhoCastro

 I was wondering how you have gotten on given the extra information and further questions from Afira above?
 
 Cheers

**Comment by RafaelCastilhoCastro** [comment]
Hi team,
Thank you for the assist. Unfortunately we're still not able to identify the problem on this subject. Due to our deadline we opted to take an alternative solution. We intend to get back to this matter in the future and get it working properly. I'll close this issue for now. We appreciate the support. Thank you.

**Comment by Anthony-Johnson-i2** [comment]
Thank you for your feedback,
