### ISSUE TITLE
Capture username on the connector

### ISSUE THREAD

**Issue by RafaelCastilhoCastro** [i2group/analyze-connect#21]
Hi, 
Can you advise on how can we obtain on the connector the name of the user logged on ANB? Apparently its possible using the i2 Notebook SDK but it doesn't seems to be available in Python. We only found it available for Java and Node applications. Can you please advise how can we do it on a Python connector?

Thank you.

**Comment by Ricardo-Antunes-i2** [comment]
Hi @RafaelCastilhoCastro,

The user principle is provided to a connector via the following header **I2-Principal** (see: https://i2group.github.io/analyze-connect/content/example-connectors/user-configuration.html) in the request.

If you would like to provide more customized information to the connector you can also make use of custom header mechanism (see: https://i2group.github.io/analyze-connect/content/miscellaneous/principal-propagation.html).

**Comment by RafaelCastilhoCastro** [comment]
Hi @Ricardo-Antunes-i2,
Thank you for your response!

This solution almost solves our needs. But the issue is that ANB caches the user data on first access and doesn't send the header to the connector on following accesses of the same user. Is it possible to disable this cache functionality or to force ANB to send the header on every new access?

**Comment by Anthony-Johnson-i2** [comment]
Hi @RafaelCastilhoCastro 

If you make use of [Principal propagation](https://i2group.github.io/analyze-connect/content/miscellaneous/principal-propagation.html ) 

You will find that the extra header information is propagated to the connector with each request but it is added by and sent on from the Gateway and not from ANBP so you may have missed this happening.

Cheers

**Comment by RafaelCastilhoCastro** [comment]
Hi @Anthony-Johnson-i2,
We instructed the i2 gateway to send the headers in requests and it worked. But as it is now it only works for the first access of each user. As explained on this paragraph below, the gateway is caching that information and not propagating it to the connector with each new log in. 
![image](https://github.com/i2group/analyze-connect/assets/65736872/d8007433-a3ff-49be-ab0d-8b5ed4914f03)

Could you advise on how to set that information to be propagated with each request as you mentioned?

Thanks!

**Comment by RafaelCastilhoCastro** [comment]
Hi @Colvin-Cowie-i2,
Now I see. I can capture the headers on all endpoint if necessary. Sorry it took so long to get it. That solves our issue.
Thank you for your support everyone!
