### ISSUE TITLE
Specify security attributes

### ISSUE THREAD

**Issue by chriiisiscoding** [i2group/analyze-connect#23]
The entities and links that my connector returns seem to default to the same security attributes (e.g., Security Compartment and Security Level). But I need to be able to adjust those depending on the data that the connector returns. How can pass in security information in my connector response payload?

**Comment by Colvin-Cowie-i2** [comment]
Hello, I'm afraid that return of security dimension values isn't currently supported in i2 Connect.
The client itself (e.g. ANBP) sets the security dimension values of new records on the chart based on the defaults specified on the server https://docs.i2group.com/analyze/4.4.2/t_set_default_security.html, but these are not based on the record's properties.

**Comment by chriiisiscoding** [comment]
Thank you for the clarification! That probably prevents us from using connectors entirely, unfortunately.

**Comment by Colvin-Cowie-i2** [comment]
If you have support entitlement, you can raise a support [request](https://i2group.com/support-request) referencing this issue and it can be raised as a Request for Enhancement (RFE) .

**Comment by enpm611** [comment]
I do and I will. Thank you!
