### ISSUE TITLE
Entities are duplicated when added to chart

### ISSUE THREAD

**Issue by chriiisiscoding** [i2group/analyze-connect#25]
This is a continuation of this thread:

https://github.com/i2group/analyze-connect/issues/22#issuecomment-1738998532

where @Colvin-Cowie-i2 already gave some great advice.

The issue here is that when I perform a search and I repeatedly add the same entity to the chart, it will be duplicated on the chart:

<img width="998" alt="image" src="https://github.com/i2group/analyze-connect/assets/15349825/c7a26ed7-47c8-48a1-905c-600c8a3d25ce">

I followed the advice by making sure that I set `"resultIdsPersistent": true` and to return a [source identifier](https://i2group.github.io/analyze-connect/content/miscellaneous/source-identifiers.html). To make things easier to debug, I created a copy of the NYPD example connector:

https://github.com/chriiisiscoding/nypd

I made the following changes from the original code:
- stripped out services that are not needed to make my point
- I replaced the NYPD API call with sample data
- changed the SPI version to `1.0` since my gateway only supports up to `1.1` and my other custom connector is version `1.0`.
- Made the source identifier changes suggested [here](https://i2group.github.io/analyze-connect/content/miscellaneous/source-identifiers.html)

I should also mention that when I make a change to my service, I run

```bash
./setup -t restart
```

I hope that is sufficient and I don't have to deploy every time I change the config?

As you can see, the connector still creates duplicate entities. You should be able to reproduce this using my repo.

Thank you!

**Comment by Colvin-Cowie-i2** [comment]
Can you also confirm the
 - version of Analyst's Notebook
 - version of i2 Analyze
 - what deployment pattern you are using (e.g. `daod-opal`, `chart-storage-daod` or `information-store-daod-opal`)
 - have you configured system match rules with source identifier matching https://docs.i2group.com/analyze/4.4.2/configuring_smr.html? (Note: the steps are different depending on the deployment pattern)

**Comment by chriiisiscoding** [comment]
I know that we have Analyst's Notebook Premium version `9.4.1`

I'm not sure how to answer your other questions. Regarding the version of i2 Analyze, I have this output from when I restart the server:

```
========================= Toolkit ==========================
Installation Path: ...
Version: 4.4.1.0-29666
Applied Fixes:
        4.4.1.1
```

Regarding the deployment pattern, I see this in the logs:

```
Starting server opal-server.
Server opal-server started with process ID 8456.
Monitoring /opt/ibm/i2Analyze/deploy/wlp/usr/servers/opal-server/logs/console.log for application status.
Waiting for 'opal-services-is' application to start...
```

I believe we have not configured any matching rules.

**Comment by chriiisiscoding** [comment]
I can confirm that we don't have any matching rules specified in the server, but there seems to be a default rule specified in ANB:

<img width="992" alt="image" src="https://github.com/i2group/analyze-connect/assets/15349825/12ddbda6-3b50-4b64-a86e-8e978900fa30">

which would merge the two entities:

<img width="1165" alt="image" src="https://github.com/i2group/analyze-connect/assets/15349825/e9f458c3-f26c-4db6-93b6-0dc78e8905cf">

**Comment by chriiisiscoding** [comment]
Thank you @Colvin-Cowie-i2 ! This explains everything. I'll try to set up those matching rules and deploy them. I will confirm here when/if I get it to work. Thanks again!

**Comment by chriiisiscoding** [comment]
I created a rule file and stored it in 

```
.../i2analyze/toolkit/configuration/environment
```

while the [documentation]() said I should place it in the `live` directory, there was no such directory and the existing (yet fairly empty) `system-match-rules.xml` as in the `environment` directory. I ran `updateMatchRules` and then `restart` on the server. But when I run the query and add the same entity, I still get duplicates. Am I assuming correctly that the matching rules should automatically fire and merge entities as I add them to the chart?

Rules:

```xml
<?xml version="1.0" encoding="utf-8"?>
<tns:matchRules xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.i2group.com/Schemas/2019-05-14/MatchRules MatchRules.xsd " version="2" enableSourceIdentifierMatching="true" xmlns:tns="http://www.i2group.com/Schemas/2019-05-14/MatchRules">
  <matchRule id="41212390-0324-4efc-8753-6b4d03a336a2" itemTypeId="ET1-nypd-complaints" displayName="Complaints Rule" version="1" description="" active="true">
    <matchAll>
      <condition propertyTypeId="PT1-nypd-complaints">
        <operator>EXACT_MATCH</operator>
        <normalizations>
          <normalization>IGNORE_CASE</normalization>
          <normalization>IGNORE_DIACRITICS</normalization>
          <normalization>SIMPLIFY_LIGATURES</normalization>
          <normalization>IGNORE_WHITESPACE_AROUND</normalization>
        </normalizations>
      </condition>
    </matchAll>
    <matchAny xsi:nil="true" />
  </matchRule>
</tns:matchRules>
```

**Comment by Colvin-Cowie-i2** [comment]
The live directory is for the i2 Connect standalone pattern, where you don't have an information store.
Did you follow the instructions here https://docs.i2group.com/analyze/4.4.2/creating_smr_is.html, including step 7?
> Update the application to use the standby match index:
>
>setup -t switchStandbyMatchIndexToLive
>
>This toolkit task switches the standby match index for your new rules to the live index. The match index that was live is now the standby match index.

**Comment by chriiisiscoding** [comment]
That worked! Thanks so much! It's been a common complaint from users. They'll be thrilled when we get this deployed. Thanks again! This can be closed.

**Comment by Colvin-Cowie-i2** [comment]
Great, I'm glad you've got it sorted :)
