### ISSUE TITLE
Remove labels from links

### ISSUE THREAD

**Issue by chriiisiscoding** [i2group/analyze-connect#28]
I'm not sure if this is the right forum to address my issue but you guys have been most helpful so I thought I'd bring it up here since I can't seem to find a solution.

I created a connector schema. In that schema, I didn't modify the Charting Schemes to set any properties for the links. Now, they show up with this really large label just as you can see on this page:

https://docs.i2group.com/analyze/4.4.0/mapping-connector-to-gateway.html

Do you know how I can control the label so that it doesn't show the connector name and even potentially remove the type of relationship (since that's often obvious to users). The only information we would want to show is a count of how many links are collapsed into one.

Again, if this is the wrong forum, I apologize.

**Comment by Anthony-Johnson-i2** [comment]
Hi Chris

I am out until next week, but have mentioned your issue on one of our internal dev channels so hopefully someone will get back to you on this before my return.

Cheers

**Comment by chriiisiscoding** [comment]
Thank you so much! I very much appreciate your help.

**Comment by Anthony-Johnson-i2** [comment]
Hi Chris 

I can see [here](https://i2group.github.io/analyze-connect/content/walkthrough/2-deploy-i2-analyze.html?q=label) that we state that the short name will appear in the labels of links.

You can control that short name so can mitigate things by making it shorter perhaps.

As for the rest of what you are seeing on the link labels perhaps by specifying the label format in the charting scheme used by your connector you could override the default display somewhat.

I have not had an answer yet as to whether it is possible to remove labels completely from links charted from external sources like this.

Cheers

**Comment by chriiisiscoding** [comment]
Thank you for looking into this!

**Comment by Andrew-Stawarz-i2** [comment]
What you are observing is the default behaviour when no charting scheme information has been provided for types in the connector schema. For link it will fall back to using the schema link type's display name for the chart surface link label. As the link type is from an i2Connect connector schema the display name, as highlighted earlier, will differ from what is in the schema by having an additional suffix of " - <short connector name>" that cannot be removed.

What can you do? You will will need to create, and deploy, a charting scheme in Schema Designer for your connector schema to tailor what information you wish to see on the chart link. Once in Schema Designer, from the File menu select "Edit Charting Schemes..."

![image](https://github.com/i2group/analyze-connect/assets/97096500/21b1e953-92c8-427f-aa8a-09167e5e838f)

An i2Connect connector only supports a single charting schema so prune down the default list presented to 1 single one by selecting and deleting the others.

For a count of records on a summarised link select your link type and set the summarisation to Single:

![image](https://github.com/i2group/analyze-connect/assets/97096500/bc62c6fa-f237-4ac1-9f35-52e70b2cf68e)

Then you'll need to add a property mapping for the link label, expand the link type and right-click on "Properties" and click on "Insert Chart Item Property Type":

![image](https://github.com/i2group/analyze-connect/assets/97096500/3dd576f2-f9e9-43ee-b5bb-3793f7882c75)

and select "Label" in the dialog that then opens and then OK:

![image](https://github.com/i2group/analyze-connect/assets/97096500/40c13f78-8dd8-42c9-89b4-b1f7babc959e)

From the "Insert" button drop-down menu you are then able to pick what you'd like to have displayed:

![image](https://github.com/i2group/analyze-connect/assets/97096500/2bfca584-31ff-458f-aa1f-50bf1ea941a9)

One of the options is "Summarized Link Count".

![image](https://github.com/i2group/analyze-connect/assets/97096500/a6e109bf-f694-4c97-9474-015689aa11a0)

Once selected you should then be click OK to close the Charting Scheme editor to return to the main Schema Designer dialog to then save the changes.

**Comment by chriiisiscoding** [comment]
This is amazing, guys. Thank you for all the research, effort, and detailed instructions! I will definitely give that a try.

**Comment by Anthony-Johnson-i2** [comment]
Hi @chriiisiscoding  

How did you get on with Andrew's suggestions?
Are you Ok for this issue to be closed now?

**Comment by chriiisiscoding** [comment]
Yes, that worked for us. Thank you again so much! This can be closed.
