### ISSUE TITLE
Request for Enhancement

### ISSUE THREAD

**Issue by CharlesMarriott-VA** [i2group/analyze-connect#29]
Is it possible to have a form similar to the login form where we can capture user input before the user interacts with the services?

We need to have access to a session variable where the value of this determines what sql tables are accessible. At present, we provided a dropdown at the service level to capture this, which was rejected by the client. It would be good if we could have/construct a form, post sign in, that could ask the user to select an option from a dropdown box and store that selection in a way that all services can access.

Is it possible to have this type of functionality added?

**Comment by Ricardo-Antunes-i2** [comment]
Hi @CharlesMarriott-VA,

Have you looked into i2 Connect [user specific configuration](https://i2group.github.io/analyze-connect/content/example-connectors/user-configuration.html) feature? This would allow you to decide how to present a form based on the user trying to access it.

**Comment by Anthony-Johnson-i2** [comment]
Hi @CharlesMarriott-VA 

Did the suggestion from Ricardo allow you to do what you wanted?

**Comment by Anthony-Johnson-i2** [comment]
I will close this one out as we have not had a response which hopefully means @Ricardo-Antunes-i2  suggestion helped.
Cheers
