### ISSUE TITLE
Attribute 'gateway-schema' is not allowed

### ISSUE THREAD

**Issue by r00t1ng** [i2group/analyze-connect#3]
Hi,

when running the setup -t deploy I get the following error:
 + configuration/environment/topology.xml:
   - The structure of the topology XML was invalid: cvc-complex-type.3.2.2: Attribute 'gateway-schema' is not allowed to appear in element 'connector'.

**Comment by matthadf** [comment]
Hi @r00t1ng , which version of i2 Analyze are you using?

You can find this at the top of any of the log files in the `toolkit/configuration/logs` directory.

Thanks,
Matt

**Comment by r00t1ng** [comment]
Hi @matthadf 

I am running 4.3.3 and 9.3.2 ANB Premium.

Thank you

**Comment by matthadf** [comment]
Thanks @r00t1ng , that is the right version.

Can you copy the contents of your `configuration/environment/topology.xml` file for us to take a look at?

Thanks

**Comment by r00t1ng** [comment]
Sure, is it possible to send it via e-mail at this point?

**Comment by matthadf** [comment]
Hi @r00t1ng , is it possible to redact all identifying information?

We do not need to see host names / ip addresses / file paths. More the attributes that are included in the <connector> element.

**Comment by Colvin-Cowie-i2** [comment]
I believe this issue was resolved. @r00t1ng feel free to reopen if necessary.
