### ISSUE TITLE
i2 connect autentication

### ISSUE THREAD

**Issue by SVValen** [i2group/analyze-connect#30]
Hello,
We are implementing i2 connect authentication, using the user-pass method.
Our question is whether it is possible to specify the time at which the authentication form is displayed.
Currently we have developed it so that the service form that has authentication is displayed, it is completed and when the execute button is clicked, the authentication form is displayed.
Our question is whether it is possible to specify that the authentication form be displayed before the service form is displayed.
I hope I have explained myself.
Any help is useful, thanks!

**Comment by Afira-Zahari-i2** [comment]
Hi @SVValen, it is _not_ possible to have the authentication form displayed before the service form. It will only be displayed when the service is _executed_.

**Comment by SVValen** [comment]
Hi @Afira-Zahari-i2, thanks for your help!
