### ISSUE TITLE
Changing label of link

### ISSUE THREAD

**Issue by sdorresteijn88** [i2group/analyze-connect#31]
Good morning,

I tried to add a label to my link. But I don't get it working and I don't get a proper error message.

When I remove the phoneLink.setProperties it works as expect, except that the label is not set.

![image](https://github.com/i2group/analyze-connect/assets/52672945/75427648-6ef8-454a-a9fc-0de58526d902)

```
const phoneData: Phone = {
                phoneNumber: flightData.passengerInfo.phoneNumber
              };
              const phone = addPhone(phoneData, result);
              const phoneLinkID = `${flightData.passengerInfo.phoneNumber}-${passengerID}`;
              addLink(Communication, phoneLinkID, seedEntity, phone, result);
              const phoneLink = result.getLink(Communication, phoneLinkID);
              if (phoneLink){
                const phoneProps = {
                  'Description': 'Communication'
                }
                phoneLink.setProperties(phoneProps);
              }
```

![image](https://github.com/i2group/analyze-connect/assets/52672945/815823e9-f62e-4ced-9011-480c5b35a8a3)

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88  

There are  a couple of other issues that may be of use to you here  ( one is yours from last year)

https://github.com/i2group/analyze-connect/issues/26

and 

https://github.com/i2group/analyze-connect/issues/28

The second one is about how to remove labels but does talk about how to alter them in general as well.

What sort of field is the Description in your schema?

Cheers

**Comment by sdorresteijn88** [comment]
@Anthony-Johnson-i2 thank you for you reply. I like the idea of #28 so I added default text to the labeling schema. This fixed the issue, but now I ran into a next issue.

i2 Notebook is freezing when I copy the entities to the chart.

1. The <Label> is replaced with text.
![image](https://github.com/i2group/analyze-connect/assets/52672945/cce85f19-9fe3-4d66-b4cc-a58d27e806d8)

2. Then this message will appear
![image](https://github.com/i2group/analyze-connect/assets/52672945/f2559d0b-63d2-42e8-9cba-a319f7810b96)

3. I can't see any errors in the console
![image](https://github.com/i2group/analyze-connect/assets/52672945/80192f5f-a84d-4dc7-bcaa-e68fda1e0cd4)

4. This is how the labeling scheme and charting scheme looks like
![image](https://github.com/i2group/analyze-connect/assets/52672945/16e36481-e011-4914-ad5a-e1135eaf232b)

5. In ANBP it works as before and without issues

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88 

Apologies for there being no response to this over the last couple of weeks since I last pinged you. 

Have you managed to solve this yourself whilst I was out of office?

If you are still having no luck with this, I will dig around a bit and see if we are best to try and  progress things further here or whether we would be best to escalate this via a support case.

Cheers

**Comment by Anthony-Johnson-i2** [comment]
Hi @sdorresteijn88 
I started having more of a look into what you are experiencing here.

A big difference with label display in i2 Analyst's Notebook Premium and i2 Notebook is that i2 Notebook  does not use the Charting Scheme at all , it only uses the default Labeling Scheme that comes with the schema. 

This explains why you see the labels more as you expect in  i2 Analyst's Notebook Premium as it uses a combination of the Charting and labeling schemes there.

What is very odd however is why, when you define the labels in the labeling scheme as you have done, they display correctly in the results list but you can not chart in i2 Notebook.

I notice that one of the links you do this for has no properties and you just create the label using a free text entry for the labeling scheme based label 'Location'  to  try and mimic what you get in the charting scheme to display what sort of link it is.

It would be interesting to see if you could get anything to appear in your link labels for one link type and could still chart in i2 Notebook if you only added a labeling scheme definition in for a link that has properties that you could use  for example: the Passenger link using the Seat Number and Passenger ID properties in the label.

In general the labeling scheme works well but you seem to have hit a strange case here.

I have a feeling that you may have found an edge case with the i2 Notebook charting hang when you are using your labeling scheme so if you wouldn't mind, could you raise a case for it and we will dig more deeply in to that officially via a support case and Escalation route.

Reference this gitHub Issue in that, and I will let folks here know to escalate when it arrives.

Cheers

**Comment by sdorresteijn88** [comment]
Hi @Anthony-Johnson-i2 thanks for your detailed reply! Good to know that i2 Notebook only uses the Labeling Scheme. 

I'll create a support ticket for this with a reference to this issue.
